#!/usr/bin/env python3
"""web/suite.html -> src/lora_node/web_suite.h (the chalet web suite, kept in flash as one PROGMEM string).

Run by PlatformIO before each build (extra_scripts in platformio.ini) and by tools/build_check.sh; the
generated header is committed too, so a build without Python still works. Edit web/suite.html, never the .h.
Preview on a PC with fake data: python3 tools/web_preview.py (reads web/suite.html).
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "web", "suite.html")
DST = os.path.join(ROOT, "src", "lora_node", "web_suite.h")
MAX_CHUNK = 60000   # a raw string literal is split into chunks the compiler concatenates (MSVC-safe, gcc fine)

def main():
    html = open(SRC, encoding="utf-8").read()
    if ')rawliteral"' in html:
        sys.exit("suite.html must not contain )rawliteral\"")
    out = ["// GENERATED by tools/gen_web.py from web/suite.html - edit the .html, not this file.",
           "#pragma once", "#include <pgmspace.h>",
           "static const char SUITE_PAGE[] PROGMEM ="]
    for k in range(0, len(html), MAX_CHUNK):
        out.append('R"rawliteral(' + html[k:k + MAX_CHUNK] + ')rawliteral"')
    out[-1] += ";"
    out.append("")
    text = "\n".join(out)
    old = open(DST, encoding="utf-8").read() if os.path.exists(DST) else None
    if old != text:
        open(DST, "w", encoding="utf-8").write(text)
        print("web_suite.h: %d bytes of HTML" % len(html))

if __name__ == "__main__":
    main()
# PlatformIO extra_scripts entry point
try:
    Import("env")  # noqa: F821
    main()
except NameError:
    pass
